
packages = ["xarm_description", "robotiq_85_description"]
starting_joint_values= [0.0, -1.2, -0.15, 0.1, -0.1, 1.57]
approach_dist= 0.05 

[urdf_paths]
robot= "urdfs/xarm6_grip.urdf"
obstacle= "urdfs/obstacles.urdf"

[links]
base= ["link_base"]
ee= ["gripper_center_link"]
used_joints= [
    "joint1",
    "joint2",
    "joint3",
    "joint4",
    "joint5",
    "joint6",
]

